#!/bin/sh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="cli_utilities,dmscripts,git,other_config,shell,terminal,tmux,vim(s),window_managers"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

