#!/bin/sh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="dmscripts,git,imwheel,leftwm,qtile,shell,terminal,tmux,vim(s)"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

