theme = "gruvbox"

[editor]
line-number = "relative"
scrolloff = 8
idle-timeout = 0
cursorline = true
auto-format = false
rulers = [80]

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.indent-guides]
render = true
