[[language]]
name = "rust"
auto-format = false

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "    " }
